import fontina from './images/productos/fontina.jpg'
import fontinamini1 from '../components/images/productos/fontina.mini.jpg';
import crudoEspañol from './images/productos/crudoespañol.jpg';
import crudoEspañolmini from '../components/images/productos/crudoespañol.mini.jpg'
import tabla1 from './images/productos/tablas.jpg'
import tabla1mini from '../components/images/productos/tablas.mini.jpg'
const PRODUCTOS = [
    {
        "id": "01",
        "categoria": "quesos",
        "nombre": "Fontina",
        "imagen": `${fontina}`,
        "miniaturas": [fontinamini1, fontinamini1, fontinamini1],
        "descripcion": "Queso tipo frances con estacionamiento especial y sensacion picante",
        "precioNormal": 1600,
        "precioOferta": 1450,
        "stock":10,
    },
    {
        "id": "02",
        "categoria": "quesos",
        "nombre": "Gruyere",
        "imagen": `${fontina}`,
        "miniaturas": [fontinamini1, fontinamini1, fontinamini1],
        "descripcion": "Queso tipo frances con estacionamiento especial y sensacion picante",
        "precioNormal": 1600,
        "precioOferta": 1450,
        "stock":15,
    },
    {
        "id": "03",
        "categoria": "quesos",
        "nombre": "Pategras",
        "imagen": `${fontina}`,
        "miniaturas": [fontinamini1, fontinamini1, fontinamini1],
        "descripcion": "Queso tipo frances con estacionamiento especial y sensacion picante",
        "precioNormal": 1250,
        "precioOferta": 1056,
        "stock":15,
    },
    {
        "id": "04",
        "categoria": "fiambres",
        "nombre": "Jamon Crudo Español",
        "imagen": `${crudoEspañol}`,
        "miniaturas": [crudoEspañolmini, crudoEspañolmini, crudoEspañolmini],
        "descripcion": "Jamon crudo de cerdo con 12 meses de estacionamiento y bajo nivel de sodio.",
        "precioNormal": "360",
        "precioOferta": "341",
        "stock":10,
    },
    {
        "id": "05",
        "categoria": "fiambres",
        "nombre": "Jamon Crudo Español",
        "imagen": `${crudoEspañol}`,
        "miniaturas": [crudoEspañolmini, crudoEspañolmini, crudoEspañolmini],
        "descripcion": "Jamon crudo de cerdo con 12 meses de estacionamiento y bajo nivel de sodio.",
        "precioNormal": "360",
        "precioOferta": "341",
        "stock":30,
    },
    {
        "id": "06",
        "categoria": "fiambres",
        "nombre": "Jamon Crudo Español",
        "imagen": `${crudoEspañol}`,
        "miniaturas": [crudoEspañolmini, crudoEspañolmini, crudoEspañolmini],
        "descripcion": "Jamon crudo de cerdo con 12 meses de estacionamiento y bajo nivel de sodio.",
        "precioNormal": "360",
        "precioOferta": "341",
        "stock":35,
    },
    {
        "id": "07",
        "categoria": "picadas",
        "nombre": "Clasica",
        "imagen": `${tabla1}`,
        "miniaturas": [tabla1mini, tabla1mini, tabla1mini],
        "descripcion": "Jamon crudo, lomo horneado, bondiola cerrana, queso condimentado, mar del plata, salamin picado grueso, leber y aceitunas",
        "precioNormal": "1500",
        "precioOferta": "1380",
        "stock":10,
    },
    {
        "id": "08",
        "categoria": "picadas",
        "nombre": "Clasica",
        "imagen": `${tabla1}`,
        "miniaturas": [tabla1mini, tabla1mini, tabla1mini],
        "descripcion": "Jamon crudo, lomo horneado, bondiola cerrana, queso condimentado, mar del plata, salamin picado grueso, leber y aceitunas",
        "precioNormal": "1500",
        "precioOferta": "1380",
        "stock":10,
    },
    {
        "id": "09",
        "categoria": "picadas",
        "nombre": "Clasica",
        "imagen": `${tabla1}`,
        "miniaturas": [tabla1mini, tabla1mini, tabla1mini],
        "descripcion": "Jamon crudo, lomo horneado, bondiola cerrana, queso condimentado, mar del plata, salamin picado grueso, leber y aceitunas",
        "precioNormal": "1500",
        "precioOferta": "1380",
        "stock":10,
    }
];

export default PRODUCTOS;